"""initial tables

Revision ID: 94dceab944e2
Revises: 
Create Date: 2026-01-14 09:00:10.879225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94dceab944e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_tags_tag'), table_name='test_tags')
    op.drop_index(op.f('ix_test_tags_test_id'), table_name='test_tags')
    op.drop_table('test_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('test_tags_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('test_tags_pkey'))
    )
    op.create_index(op.f('ix_test_tags_test_id'), 'test_tags', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_tags_tag'), 'test_tags', ['tag'], unique=False)
    # ### end Alembic commands ###
